spring:
  datasource:
    url: jdbc:h2:file:D:/H2_DB/groovy-mix/db
    username: root
    password: admin
  jpa:
    # 切换InnoDB引擎
    # H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
management:
  endpoint:
    health:
      show-details: always